### ISSUE TITLE
Error: Invalid Transaction Signature

### ISSUE THREAD

**Issue by pynchmeister** [zapproject/zap-oracle-template#15]
## Background

https://github.com/zapproject/zap-oracle-template/wiki/Steps-to-test-Oracle-Query-Response

## Summary 

Although the guide linked above found success with the UCONN students. We are running into errors recreating a query/response. The issue seems to be isolated within zap-oracle template and occurs after ```npm start``` is run.

Here are the error logs: 

```Wallet contains: 9999.725104 ETH ; 1500000000000.0000000000007 ZAP
Provider's title:  
No provider found, Initializing provider
Error: Invalid transaction signature
    at Object.callback (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:18:36)
    at /Users/btccenternyc/newnew/zap-oracle-template/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:196:13)
    at WebSocketConnection.processFrame (/Users/btccenternyc/newnew/zap-oracle-template/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /Users/btccenternyc/newnew/zap-oracle-template/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:81:9)
```

If you have any ideas as to the source of the issue, please post in this thread.

**Comment by pynchmeister** [comment]
Alex and I tried to revert to this commit: 65035681c8e1fb811ade94833ac88b329313b845

These are the corresponding error logs:

![unknown-2](https://user-images.githubusercontent.com/33232379/112550176-56c00380-8d95-11eb-887b-7c5c6105b471.png)
